---Version + API-version metadata for auto-core.nvim.
---
---`version` is the package version (`v0.X.Y` git tag — used by lazy.nvim
---when consumers pin via `version = "^0.X.0"`). It bumps on every
---release.
---
---`api_version` is a SEPARATE semver string covering the public Lua
---surface (`require("auto-core").events`, `.state`, `.ui`, `.fs`,
---`.git`, `.tasks`, `.log`, `.health`). It bumps independently of
---`version`:
---  - patch: bug fixes only, no API change
---  - minor: API additions (new functions, new topics, new state keys)
---  - major: API removals or behavior changes
---
---Consumers branch on `api_version` when they need feature-detection
---without pinning a specific package version:
---
---  if require("auto-core").api_version >= "0.2" then ... end
---
---v0.1.0 (2026-05-11) is the **solid beta** — first release covered
---by the `auto-core-maintenance` convention's additive-only minor-
---bump rule. Consumers can safely pin via `version = "^0.1.0"` (caret)
---and trust that no future v0.X.Y will rename, remove, or break-shape
---any existing function, state key, topic, or persisted schema.
---
---@module 'auto-core.version'

return {
  -- v0.1.8: per-instance mailbox isolation. `register("agent:foo")`
  -- now stores the mailbox under `<root>/agent:foo:<instance_id>/`
  -- where instance_id = `<unix-seconds>-<pid>` for this nvim
  -- process. Two nvims sharing a tool root coexist cleanly — no
  -- lock, no cross-talk, hard-isolation by directory. Bootstrap
  -- doc hoisted to `<tool-root>/bootstrap-mailbox.md` (shared
  -- across all mailboxes in that root) with agent identity now
  -- carried via spawn-time env vars rather than per-call template
  -- substitution. Adds `mailbox.env_for_agent(record)` and
  -- `mailbox.prune({ root, max_age_seconds })` helpers. Event
  -- payloads carry bare ids in `mailbox` / `from` fields with
  -- `_full` / `_resolved` companions for cross-instance routing.
  -- Persisted schema change (mailbox dir layout) shipped as patch
  -- per user decision; only known consumer (auto-agents) updates
  -- alongside.
  -- v0.1.9: bootstrap template update. The agent-facing protocol
  -- doc (`templates/bootstrap.md`) now references `wake` instead
  -- of `send_slot` as the canonical wake command name and adds a
  -- new section explaining the `addressbook` discovery command.
  -- schema_version bumped 2 → 3 because the renamed command name
  -- is a public-API contract change agents must re-acknowledge.
  -- No Lua-API change — `mailbox.commands.register` consumers
  -- (auto-agents v0.2.8+) already register `wake` + `addressbook`
  -- with the registry.
  -- v0.1.10: git.graph.fan_out — `is_bare` now reflects the
  -- underlying repo's bareness (read from `<common_dir>/config:
  -- core.bare`) rather than the probed dir's. Probing from inside
  -- a linked worktree of a bare repo previously returned
  -- is_bare=false because `rev-parse --is-bare-repository` reports
  -- the working-tree's bareness, not the repo's — causing
  -- worktree.nvim's `C` (checkout) keybind to fall into the plain
  -- `git checkout` branch instead of `git worktree add --track`.
  -- No API shape change; AutoCoreGraphRepo.is_bare semantics
  -- clarified, not renamed.
  -- v0.1.11: ADR 0021 Phase 1 — centralized log surface for the
  -- family. Additive extensions to `auto-core.log` (no removals,
  -- no break-shape):
  --   - AutoCoreLogEntry gains optional `event_type` and `fields`
  --     fields; both nil for pre-ADR-0021 emissions
  --   - level_call accepts a trailing options table whose
  --     recognition is keyed on sentinel keys (event / fields /
  --     notify / level_override); ordinary message-part tables
  --     keep rendering via vim.inspect unchanged
  --   - log.notify(msg, opts?) — single-emission ring write +
  --     forced vim.notify toast
  --   - log.notifyIf(event, msg, opts?) — ring write + toast iff
  --     event is in the user's subscribed set
  --   - log.events.{register, list, enable_notify,
  --     disable_notify, is_notify_enabled} — plugin-registered
  --     event registry; subscriptions persist via
  --     auto-core.state.namespace("auto-core.log.events")
  --   - log.<level>_throttled(key, every_ms, ...) — hot-loop guard
  --     family for every level
  --   - :AutoCoreLogEvent list | notify <event> | silence <event>
  --     user command with context-aware tab completion
  -- See ADR 0021 + shared/conventions/auto-family-logging.md for
  -- the wrapper convention each consumer plugin should follow.
  -- v0.1.12: mailbox.router executor `ctx` now surfaces the
  -- sender's identity as `sender` (msg.from verbatim) and
  -- `sender_bare` (`mb_path.bare_id(from)`) alongside the existing
  -- `mailbox` / `mailbox_full` executor fields. Closes a latent
  -- attribution gap: command handlers that wanted "who asked me to
  -- do this" had to guess from `ctx.mailbox`, which is the EXECUTOR
  -- (always `nvim`), not the sender. Surfaced for the auto-agents
  -- `diff_queue` handler — see auto-agents v0.2.12 Patch 4 + ADR
  -- 0011 §D3 for the consumer side. Additive; no removals; existing
  -- consumers reading `ctx.mailbox` continue to work unchanged.
  -- v0.1.13: ADR 0023 Phase 1 + log :messages silence. Three
  -- additive changes:
  --   1. `log.lua`: INFO+ is RING-ONLY by default — toasts no
  --      longer leak to `:messages` unless caller passes
  --      `opts.echo = true` (per-call) or `configure({ echo =
  --      true })` (global). ERROR + WARN still toast as before.
  --      Pre-v0.1.13 behavior was firehose `:messages` echo on
  --      every emission; new default mirrors the
  --      auto-family-logging convention's "no noisy :messages"
  --      stance.
  --   2. `mailbox/router.lua`: classify() now emits the new event
  --      topic `mailbox.stale_orphan_detected` whenever a poll
  --      finds an outbox path whose mailbox component matches a
  --      KNOWN bare id but at a NON-CURRENT instance suffix.
  --      Payload carries `{ mailbox_bare, observed_instance,
  --      current_instance, path }`. Subscribed via
  --      `auto-core.log.events` for the resumed-agent diagnostic
  --      (per ADR 0023 §3.1). Existing classification outcomes
  --      unchanged; this is a pure observability addition.
  --   3. `mailbox/router.lua` + `templates/bootstrap.md`: wake
  --      payloads now carry `identity_hint` (the live full
  --      mailbox id) so resumed agents can detect drift between
  --      their fork-frozen `$AUTO_AGENTS_MAILBOX_DIR` env and the
  --      actual mailbox the host expects them to read. Bootstrap
  --      doc gains §"Resumed-agent identity reconciliation"
  --      documenting the drift, the new event, the `identity_hint`
  --      field, and the auto-agents `refresh_agent_id` verb (the
  --      latter shipped in auto-agents v0.2.13). Bootstrap
  --      schema_version bumped 4 → 5; resumed agents will see
  --      revision mismatch on next wake and re-ingest. See ADR
  --      0023 §3.1 / §3.2 / §4 for the full design.
  -- All three are additive. No removals; no break-shape; existing
  -- consumers ride through unchanged. Per
  -- `auto-core-maintenance`'s additive-only minor-bump rule this
  -- is a patch within the v0.1.x line. `api_version` stays at
  -- `0.1`.
  -- v0.1.14: six new `dbase.*` event topics registered in
  -- `lua/auto-core/events/topics.lua` for the auto-finder dbase
  -- section (ADR 0020) to publish onto:
  --   - dbase.connection:changed
  --   - dbase.call:started
  --   - dbase.call:state_changed
  --   - dbase.call:completed
  --   - dbase.call:failed
  --   - dbase.result:shown
  -- `conn_id` is marked optional (`string?`) on all four call.*
  -- topics because dbee's `CallDetails` shape carries no connection
  -- id; the bridge enriches via `get_current_connection()` which can
  -- return nil for archived/late events. Additive — no removals, no
  -- break-shape. Patch within the v0.1.x line per
  -- `auto-core-maintenance`; `api_version` stays at `0.1`.
  -- v0.1.15: bootstrap mailbox protocol doc now directs agents to
  -- persist `seen-revision` beside the shared per-tool-root
  -- `bootstrap-mailbox.md`, not only inside the instance-scoped
  -- mailbox dir. Bootstrap schema_version bumped 5 → 6 so agents
  -- re-read the corrected audit instructions. Additive doc-only
  -- patch; `api_version` stays at `0.1`.
  -- v0.1.16: panel-guard observability — every bounce + lifecycle
  -- event in `lua/auto-core/ui/panel.lua` now emits via `log.lua`
  -- so incident triage sees the full chain in the ring. Additive
  -- diagnostic-only patch; `api_version` stays at `0.1`.
  -- v0.1.17: ADR 0021 Phase 4 — `:AutoCoreLog` 3-pane snapshot
  -- viewer + JSONL dump persistence. Two new modules under
  -- `lua/auto-core/log/`:
  --   - dumps.lua — atomic JSONL export under
  --     `stdpath('cache')/auto-core/dumps/dump-<UTC>.log`. ISO 8601
  --     UTC timestamps reconstructed at export via
  --     `now_wall - (now_mono - ts) / 1000`. `dumps.{dir, scan,
  --     read, write, delete, iso_from_mono, normalize_for_disk}`.
  --   - viewer.lua — 3-pane float over `auto-core.ui.float.multi`
  --     (left = dump list, middle = entries, preview = detail).
  --     `viewer.{open, close, toggle, is_open}`. Snapshot
  --     semantics (no live tail). Bindings: 1..9 / <CR> / E / D /
  --     R (re-snapshot Memory — ADR §16 Q2 = yes) on left;
  --     / and f (substring + level filter cycle) on middle;
  --     <Tab> / <S-Tab> / <C-h> / <C-l> on any. q / <Esc>
  --     inherited from `ui.float.multi`.
  -- `:AutoCoreLog [open|close|toggle]` registered in
  -- `plugin/auto-core.lua`. Stale "Phase 1 stub" comment on
  -- `M.notifyIf` docstring scrubbed (registry shipped through
  -- v0.1.14). 44 new smoke tests across sections [50] dumps + [51]
  -- viewer; suite green at 718 passed, 0 failed. Additive — no
  -- removals, no break-shape, existing consumers ride through
  -- unchanged. Patch within v0.1.x per `auto-core-maintenance`;
  -- `api_version` stays at `0.1`.
  -- v0.1.19: ADR 0025 Phase 1 — `auto-core.git.watch` module +
  -- `core.git.state:changed` topic. Closes the refresh-trigger gap
  -- that left UI consumers (auto-finder files panel) showing stale
  -- git decorations after external `git add`/`commit`/`checkout`/
  -- `reset`: `auto-core.fs.watch`'s `DEFAULT_IGNORE` excludes
  -- `/.git/` by design, so no `core.file:*` ever fires for `.git/`
  -- mutations. Three additive changes:
  --   - `lua/auto-core/git/watch.lua` — narrow opt-in watcher that
  --     opens two non-recursive libuv `fs_event` handles per repo
  --     (git_dir/ filtered to {HEAD,index,ORIG_HEAD,MERGE_HEAD};
  --     git_dir/logs/ filtered to "HEAD"). Resolves git_dir via
  --     `git.repo.git_dir(repo_root)` so linked worktrees attach
  --     per-worktree, not to common_dir. `.lock` filenames are
  --     filtered at the publisher. Debounce 200ms. Public surface
  --     mirrors `fs.watch.start/stop/list/stop_all` + defaults.
  --   - `events/topics.lua` registers `core.git.state:changed`
  --     payload `{ repo_root, git_dir, kind = 'head'|'index'|
  --     'merge'|'reflog'|'other', path }`. Single coarse topic;
  --     `kind` discriminator lets subscribers filter.
  --   - `git/status.lua` adds a second `events.subscribe` for the
  --     new topic to invalidate its cache (the existing
  --     `core.file:*` invalidation misses `.git/`-only mutations
  --     for the same reason — fs.watch ignores them).
  -- Refs/remotes/, FETCH_HEAD, and logs/refs/remotes/ deliberately
  -- NOT watched — `git fetch` updates those and ADR 0007 Phase 3.5's
  -- `core.git.fetch:completed` already covers that case. Per ADR
  -- 0025 §2.5, `auto-core.fs.watch`'s `/%.git/` ignore stays
  -- untouched (un-ignoring would flood every subscriber with
  -- object/refs/reflog churn). Additive — no removals, no
  -- break-shape; consumers that don't call `git.watch.start` pay
  -- nothing. Section 51 smoke covers start/stop, kind classification
  -- across index/reflog/head, refs/remotes/ exclusion, .lock filter,
  -- debounce coalescing, max_handles cap, and status cache
  -- invalidation via the new topic. Suite green at 744 passed,
  -- 0 failed. Patch within v0.1.x per `auto-core-maintenance`;
  -- `api_version` stays at `0.1`.
  -- v0.1.18: ui.panel resize/lifecycle observability. New ring
  -- emissions in `lua/auto-core/ui/panel.lua`:
  --   - INFO `VimResized — terminal geometry changed` (host
  --     terminal resize: tmux pane / wezterm split / kitty grow).
  --     Anchors "what was the screen state when X happened".
  --   - DEBUG-throttled `WinResized fired` (per-panel, 250ms
  --     debounce key). Records `v:event.windows` so we see exactly
  --     which winids moved during a drag.
  --   - INFO `pin enforced — width re-clamped` when `enforce_pin`
  --     actually bounces a width back to the user pin (was silent
  --     before — sibling-plugin `:wincmd =` events left no trace).
  --   - INFO `panel window closed externally` on `WinClosed` for
  --     the panel's own winid. Catches close paths that bypass
  --     `Panel:close()` and would otherwise leave singleton
  --     tracking out of sync.
  -- Additive diagnostic-only patch; `api_version` stays at `0.1`.
  -- v0.1.21: ui.panel visibility-gap fix per yongjohnlee80/auto-agents
  -- issue #3 + incident
  -- agents/white-vision/incidents/2026-05-18-auto-agents-panel-duplicated-recurrence.md.
  -- Three changes to `lua/auto-core/ui/panel.lua`:
  --   - Defensive VimResized handler closes a regression that
  --     shipped silently with v0.1.18. The original form's
  --     field-table literal evaluated
  --     `(p:_is_open() and nvim_win_get_width(p.winid)) or nil`
  --     INSIDE the `{ fields = { ... } }` literal. When `p.winid`
  --     was racy-invalid (panel closed mid-handler), the field
  --     evaluation threw BEFORE `log_panel.info` ever ran — and
  --     the autocmd's implicit pcall swallowed the error. Net
  --     result: zero VimResized log entries in real session ring
  --     dumps despite the autocmd being correctly registered.
  --     The new form logs FIRST, computes throwable fields via
  --     explicit pcall, then refreshes width. The anchor now
  --     lands reliably.
  --   - New WinNew autocmd on the panel singleton's autocmd
  --     group. Deferred via `vim.schedule` so the new window's
  --     buffer is stable at check time. Logs INFO with
  --     `sibling_winids`, `panel_winid`, `panel_bufnr`,
  --     `marker_var`, `columns`/`lines`, and
  --     `debug.traceback("", 2)` whenever a new non-floating
  --     window appears holding the panel's tracked buffer but
  --     lacking the panel marker. Closes the visibility gap from
  --     the issue #3 investigation — previously these reflow-
  --     created siblings were invisible to the singleton's
  --     logging path because they bypassed `Panel:open()`.
  --     Detection-only — doesn't close; pairs with the next item.
  --   - New `Panel:_cleanup_unmarked_siblings()` method
  --     scheduled via `vim.schedule()` from the VimResized
  --     handler. Scans the tab for windows holding the panel's
  --     tracked buffer but lacking the marker; closes them.
  --     Runs OUTSIDE the autocmd context so `nvim_win_close` is
  --     permitted (avoids the E1312 fallback-scratch-swap dance
  --     that left the duplicate window visible in v0.1.18-v0.1.20).
  --     Logs INFO on each close; silent fast-path when no
  --     siblings exist.
  -- Section [52] smoke adds 11 assertions covering all three
  -- paths. Suite 753 passed, 0 failed. Additive — no removals,
  -- no break-shape. `api_version` stays at `0.1`. Reviewed by
  -- `agent:lector` 2026-05-18 10:30 UTC — approved.
  -- v0.1.22: Lector follow-ups from the v0.1.21 review. Two
  -- non-blocking observations addressed:
  --   - `_cleanup_unmarked_siblings` now scans
  --     `nvim_tabpage_list_wins(0)` (current tab only) instead of
  --     `nvim_list_wins()` (all tabs). Aligns with the incident
  --     language and prevents a theoretical cross-tab race where a
  --     sibling editor split in tab B holding the panel buffer
  --     would be force-closed by a VimResized cleanup pass in tab A.
  --     Panels are tab-singletons in the auto-family model; the
  --     load-bearing reflow case is intra-tab only.
  --   - Smoke section [52] now exercises the WinNew detection log
  --     path explicitly (assertion `WinNew detection logged
  --     'unmarked sibling detected (WinNew)'` + `WinNew detection
  --     did NOT close the sibling (detection-only)`). Previously
  --     the section only covered the cleanup path. Section grows
  --     11 → 13 assertions. Suite 755 passed, 0 failed.
  -- Additive; api_version stays at 0.1.
  -- v0.1.23: mailbox.router executor `ctx` now also surfaces
  -- `correlation_id` (from `claimed.correlation_id`) and `message_id`
  -- (executor-path file basename) alongside the v0.1.12 `sender` /
  -- `sender_bare` fields. Closes the round-trip-identity gap for
  -- handlers that defer a user-driven verdict past the synchronous
  -- response: auto-agents' `diff_queue` stashes both on its queue
  -- entry so the eventual reject/accept emits a follow-up message
  -- back to the originator via the standard router. Additive — no
  -- removals; existing handlers reading only `sender_bare` continue
  -- to work unchanged. Consumer side ships in auto-agents v0.2.19.
  -- `api_version` stays at `0.1`.
  -- v0.1.24: mailbox router + commands log observability. Closes
  -- the silent-router gap that left wake dispatch + command
  -- execution invisible to `:AutoCoreLog` (motivating incident:
  -- 2026-05-18 claude-backed agents Ultron + Vision missed wake
  -- nudges with zero ring entries to triage from). Two modules
  -- gain log emissions; one new event-type set is registered:
  --   - `mailbox/router.lua` — INFO on every inbox arrival
  --     (`mailbox.router.inbox_arrival`), response arrival
  --     (`mailbox.router.response_arrival`), and wake dispatch
  --     (`mailbox.router.wake_dispatched`). DEBUG when wake
  --     short-circuits on a mailbox with no wake config; WARN
  --     when wake's `wake.command` references a command not in
  --     the registry (almost always a setup-order bug).
  --   - `mailbox/commands.lua` — `M.handle_message` refactored
  --     into a logging-free `_handle_message_inner` + a thin
  --     outer that emits one structured entry per call:
  --     `mailbox.commands.command_executed` (INFO on ok=true /
  --     ERROR on `handler_error` / WARN otherwise) or
  --     `mailbox.commands.command_rejected` (WARN, covers
  --     `bad_message`, `not_a_command`, `missing_command`,
  --     `bad_args`, `unknown_command`).
  --   - `plugin/auto-core.lua` — registers all six event types
  --     under the `auto-core` plugin slug so
  --     `:AutoCoreLogEvent list` surfaces them. Subscribe via
  --     `:AutoCoreLogEvent notify <event>` to also see them as
  --     toasts (off by default — emissions are ring-only INFO).
  -- Structured fields on every entry: `mailbox`, `mailbox_full`,
  -- `arrival_kind`, `arrival_id`, `command`, `ok`, `code`,
  -- `error`, `correlation_id`, `dispatch_path` ("mailbox_wake"
  -- vs "mailbox_executioner"), `executor_mbox`. Filterable from
  -- `:AutoCoreLog` by component (`auto-core.mailbox.router` or
  -- `auto-core.mailbox.commands`) or by event id.
  -- Additive — no removals; no break-shape; existing event
  -- topics (`core.mailbox:*`, `core.command:*`) continue to fire
  -- unchanged alongside the new log entries. `api_version`
  -- stays at `0.1`. ADR 0021 §10 (router observability) called
  -- this out as deferred; this is that deferral resolved.
  -- v0.1.25: `ui.section.Registry:section_did_remount(N, bufnr)`
  -- — public hook for async-mount sections to repair their
  -- registry binding after a placeholder→real buffer swap.
  -- Motivating bug: auto-finder's dbase view returns a
  -- `shared.loading` placeholder from `get_buffer()` and swaps
  -- the real dbee drawer in via a `vim.schedule`-deferred mount
  -- from `on_focus`. Without this hook the registry's cached
  -- bufnr, buffer-local `0..9`/`q` keymaps, and panel winbar
  -- all remain bound to the discarded placeholder — the
  -- user-facing symptom is "winbar disappears on first dbase
  -- focus + numeric section-hop stops working" until a later
  -- redraw (`<leader>e` toggle, auto-agents panel open, etc.)
  -- re-triggers `_refresh_winbar`. The new method updates
  -- `_bufs[N]`, re-applies the private `apply_keymap` (only
  -- when N is the active section — keymap surface is
  -- buffer-local), and refreshes the winbar. Idempotent;
  -- short-circuits on invalid bufnr or inactive section.
  -- Additive — no removals, no break-shape; existing
  -- `Registry:focus` path is unchanged. `api_version` stays at
  -- `0.1` — the new method is small enough to ride along with
  -- the v0.1.x line's existing additive contract rather than
  -- flag an api-version minor bump on its own.
  -- v0.1.26: `fs.watch` defaults updated for large bare-repo
  -- parents. Motivating incident: `auto-finder.core.watchers`
  -- logged WARN `fs.watch start failed at <LM root>: would
  -- exceed max_handles cap (0 active + 12318 new > 1024)`; the
  -- recursive walk under a bare-repo parent with ~17 worktrees
  -- of a TS monorepo collected 12k+ dirs even though `node_modules`
  -- + `.git/` + `.bare/` were already ignored. The leftovers were
  -- ecosystem-standard build/cache dirs that everyone wants
  -- ignored. Two additive changes:
  --   - `DEFAULT_IGNORE` gains anchored patterns for `/dist/`,
  --     `/build/`, `/coverage/`, `/target/`, `/%.next/`,
  --     `/%.cache/`, `/%.turbo/`, `/%.parcel%-cache/`,
  --     `/__pycache__/`, `/%.venv/`, `/venv/`,
  --     `/%.pytest_cache/`, `/%.mypy_cache/`, `/%.ruff_cache/`,
  --     `/%.tox/`, `/%.idea/`, `/%.vscode/`. Trims the LM-root
  --     walk by ~15 % and, more importantly, prevents the
  --     known-throwaway subtrees from chewing handles in any
  --     ecosystem-standard project layout.
  --   - `DEFAULT_MAX_HANDLES` raised 1024 → 131072. The cap is a
  --     "catch a runaway bug" belt (`watch.start("/")`), not a
  --     real budget — legitimate large monorepos legitimately
  --     have tens of thousands of source dirs. 131072 = ¼ of
  --     Linux's `fs.inotify.max_user_watches` default (524288),
  --     leaving the other ¾ for everything else under the user's
  --     uid (JetBrains, file managers, other nvim instances).
  --     Callers that want a smaller cap pass `max_handles` to
  --     `watch.start` per call as before.
  -- Strictly additive. Consumers pinning `version = "^0.1.0"`
  -- pick up the change on `:Lazy update` and immediately stop
  -- hitting the cap on large bare-repo parents. Health check at
  -- `health.lua:109` already reads `watch.DEFAULT_MAX_HANDLES`
  -- so the 80 %-threshold warning auto-tracks the new value.
  -- `api_version` stays at `0.1`.
  -- v0.1.27: macOS native-recursive `fs.watch` handler — the
  -- walked-per-directory path used on Linux exhausts the macOS
  -- process fd ceiling around ~7000 dirs, at which point
  -- `vim.uv.new_fs_event` returns nil and the watcher silently
  -- loses coverage. FSEvents supports recursive watching from a
  -- single root handle on Darwin, so we use it there. The
  -- original `fix(fs.watch): use native recursive watcher on
  -- Darwin` commit (dc79b66) added the branch inline inside the
  -- existing walker; it has been reverted on main and the same
  -- logic re-introduced as a separate handler so future Darwin-
  -- only changes cannot perturb the Linux walker. Five additive
  -- changes:
  --   - `fs/watch.lua` IS_DARWIN module-load constant (one
  --     `vim.uv.os_uname()` per process, not per call).
  --   - `fs/watch.lua` `_darwin_start` / `_darwin_start_one` /
  --     `_darwin_join_event_path` — fully segregated handler
  --     section. `M.start` short-circuits into it on
  --     `IS_DARWIN and opts.recursive` BEFORE any walked code
  --     runs. The Linux walker (`start_one_dir`) is byte-
  --     identical to its pre-Darwin shape.
  --   - `fs/watch.lua` `debounce_check` gains an opportunistic
  --     prune. `state._debounce` would otherwise grow without
  --     bound (every unique full_path adds an entry forever).
  --     Pre-Darwin this leaked slowly because the Linux walker
  --     pre-filtered ignored subtrees at walk time; the Darwin
  --     handler routes every event under the subtree through
  --     `debounce_check`, so the leak is much faster on macOS.
  --     New `state._debounce_size` counter triggers an O(N)
  --     sweep (drop entries older than 100×debounce_ms) only
  --     when the live count crosses 4096 — amortized O(1).
  --     Constants `DEBOUNCE_PRUNE_THRESHOLD` /
  --     `DEBOUNCE_PRUNE_TTL_MULT` documented inline.
  --   - `health.lua` `check_fs_watch` reports
  --     `; darwin native-recursive: on` on macOS so a low
  --     active-handle count on the platform doesn't look
  --     suspicious in `:checkhealth auto-core`.
  --   - Docstring header reflects the platform asymmetry: Darwin
  --     auto-watches subdirs created AFTER `watch.start`; the
  --     Linux walker does not.
  -- Strictly additive. The Linux walker code is unchanged
  -- relative to v0.1.26; consumers on Linux pick up only the
  -- debounce prune fix and the health-check copy edit. Consumers
  -- on macOS pick up actual coverage on large workspaces for the
  -- first time. `api_version` stays at `0.1`.
  -- v0.1.28: `ui.float.multi` opener-winid capture + restore.
  -- Bug: closing a multi-pane float (e.g. `:AutoCoreLog` viewer
  -- via the buffer-local `q` keymap) left focus on whatever
  -- window nvim's default traversal picked next — frequently
  -- the auto-finder panel on the left, which is tall and
  -- therefore "wins" the next-window pick. User-visible symptom:
  -- "I closed the dumps viewer and ended up in the auto-finder
  -- tree, not back in the editor I was working in."
  -- Fix: `Float:open()` snapshots `vim.api.nvim_get_current_win()`
  -- into `self._opener_winid` BEFORE opening any pane (so we get
  -- the user's real pre-float window, not the bg). `Float:close()`
  -- snapshots the pane winids BEFORE the close loop (so it can
  -- exclude them from the restore check) and, after closing,
  -- restores focus to the opener via `nvim_set_current_win` —
  -- skipping when the opener is nil (open didn't capture), no
  -- longer valid (window closed during the float's lifetime),
  -- or was itself a pane of this float (self-spawn case).
  -- Idempotent re-open does NOT overwrite the captured opener
  -- (early-return on `is_open()` short-circuits before the
  -- capture line). Smoke section [43] adds 7 assertions:
  -- captured-on-open, focus-moved-off-opener, restored-on-close,
  -- cleared-after-close, captured-not-bg, survives-invalidated-
  -- opener (kill the opener mid-float-lifetime), and the no-
  -- restore-attempted invariant when opener went stale. Suite
  -- green at 764 / 0 (was 757 / 0). Strictly additive — no API
  -- surface change, `api_version` stays at `0.1`. Consumers
  -- pinning `^0.1.0` pick up via `:Lazy update`.
  -- v0.1.29: panel `WinNew` option-inheritance guard (ADR 0027
  -- Fix B). REVERTED in v0.1.30 — see below. The v0.1.29 commit +
  -- tag remain in git history as the record of what was tried.
  -- v0.1.30: revert v0.1.29's panel `WinNew` option-inheritance
  -- guard. Lector audit (2026-05-23) found that (a) nvim 0.12.2
  -- does not propagate `winfixbuf` / `winfixwidth` for plain
  -- `:split` / `:vsplit` / `nvim_win_call(... :vsplit ...)` /
  -- `nvim_open_win({ split = ... })` — these options are special
  -- local-window options that are not copied to new windows —
  -- and (b) legitimate non-panel producers of `winfixbuf=true`
  -- exist on the user's install (gitsigns blame split,
  -- nvim-dap-view options/console splits) which the scheduled
  -- guard could race-clear after their synchronous option-set.
  -- The originating snacks `E1513` vector is fully covered by
  -- the consumer-side `auto-vim.nvim` Fix A wrap
  -- (snacks-picker-winfixbuf.lua) which is cause-agnostic.
  -- Smoke section [53] removed in the same commit; suite returns
  -- to the v0.1.28 baseline of 761 passing. Strictly additive on
  -- the API surface (only a defensive autocmd was removed); no
  -- public function / state-key / topic shape change.
  -- `api_version` stays at `0.1`. Consumers pinning `^0.1.0` pick
  -- up via `:Lazy update`; v0.1.29's behavior is gone but no
  -- consumer was relying on the side effect (the guard was a
  -- no-op on nvim 0.12.2 anyway). ADR 0027 supersession deferred
  -- to a follow-up ADR per KB hard-rule #4.
  -- v0.1.31: ADR 0028 — panel appearance writes use explicit local
  -- scope. Closes the global-default-pollution channel that left
  -- editor windows materialized after panel open inheriting
  -- `nonumber`, `norelativenumber`, `signcolumn=no`, `foldcolumn=0`.
  -- User-visible symptom prior to the fix: one editor buffer showed
  -- no relative line numbers + no sign-column margin while a sibling
  -- buffer in an older window still looked correct (the diagnosis
  -- bait — windows opened BEFORE panels grabbed correct defaults;
  -- windows materialized AFTER panel open inherited the polluted
  -- globals). Two changes in `lua/auto-core/ui/panel.lua`:
  --   - New module-local `set_winlocal(winid, name, value)` helper
  --     that wraps `nvim_set_option_value(name, value, { win = winid,
  --     scope = "local" })`. The previous pattern was `{ win = winid }`
  --     without `scope = "local"`, which mutates the global-local
  --     DEFAULT for `number` / `relativenumber` / `signcolumn` /
  --     `foldcolumn` (verified via minimal headless repro per
  --     ADR 0028 §2.3).
  --   - The panel-open appearance block (`Panel:open`) now routes
  --     every write — number, relativenumber, signcolumn, foldcolumn,
  --     winfixwidth, winfixbuf — through `set_winlocal`. Behavior on
  --     the panel window is unchanged; the only intended difference
  --     is that future editor windows no longer inherit panel
  --     presentation defaults.
  -- Section [53] smoke adds 16 assertions: seeded global defaults
  -- survive `panel:open()`, panel window still carries the masked
  -- local values, and a fresh editor split spawned after panel open
  -- inherits the seeded editor defaults. Pre-fix this section's
  -- "global SURVIVES panel open" rows would all have failed. Suite
  -- 779 passed, 2 failed (pre-existing `[25] git.repo` fresh-empty-
  -- dir failures, unrelated to panel work). Strictly additive —
  -- no API surface change, helper is module-local, `api_version`
  -- stays at `0.1`. Consumers pinning `^0.1.0` pick up via
  -- `:Lazy update`. Polluted live sessions still need the one-shot
  -- repair documented in ADR 0028 §4.6 (`:setglobal number
  -- relativenumber signcolumn=auto`); the fix protects future
  -- sessions but cannot retroactively repair an already-running
  -- nvim. auto-agents `dock.init` carries the same `{ win = winid }`
  -- pattern at lines 225-226 and will receive the matching patch
  -- in auto-agents' next release.
  -- v0.1.36 (2026-05-26): introduces the auto-core.todo subsystem
  -- (ADR-0031) — per-project task store, one MARKDOWN file per task
  -- with YAML frontmatter. Files land under `<workspace>/.todo-list/`
  -- bucketed by status. The subsystem ships CRUD + status lifecycle,
  -- refresh with 28-day auto-archive (keyed off completed_at),
  -- reference validation with stable errors[] detected, per-workspace
  -- dir-override + known-dirs registry in state, and an import path
  -- for kb-todo-list / legacy-todos-md sources.
  --
  -- DESIGN-PIVOT NOTE (preserved in branch history): an earlier
  -- iteration on this branch shipped the same data shape as pure
  -- .yaml files and bumped to v0.2.0. After landing it, the user
  -- pivoted to .md + YAML frontmatter for Obsidian-compatibility and
  -- coherence with the KB's existing dual-surface convention (see
  -- KB_RULES R2). Because no consumer ever pinned ^0.2.0 — the YAML
  -- iteration was never published — the version stays on the v0.1.x
  -- patch line. The git history retains every YAML commit as design
  -- audit trail; the tip of `feat/todo-system` is the MD format.
  -- api_version stays at 0.1 (strictly additive surface: new module
  -- `auto-core.todo`, new state namespace `todo`, two new event
  -- topics; nothing in events/state/ui/fs/git/tasks/log/health
  -- changes shape).
  -- v0.1.37 (2026-05-26): fix KB-root resolver for the
  -- auto-core.todo reference-validation pass. The resolver in
  -- `lua/auto-core/todo/init.lua` previously preferred
  -- `AUTO_AGENTS_KB_WRITE` over `AUTO_AGENTS_KB_ROOT`, which broke
  -- validation of `shared/...`-rooted `adr:` / `review:` paths
  -- whenever KB_WRITE pointed at a sub-directory of the KB (per
  -- the auto-agents KB convention: WRITE is conventionally
  -- `<kb>/shared/` or `<kb>/agents/<name>/`, never the root
  -- itself). The join produced `<kb>/shared/shared/...`
  -- (duplicated segment) and reported every adr ref as
  -- not-found. Flipped to ROOT > READ[0] > WRITE; tests/[61]
  -- locks the new order against a realistic env shape (ROOT +
  -- WRITE both set, WRITE under ROOT). No API surface change.
  -- v0.1.38 (2026-05-26): adds `auto-core.todo.scan()`. Where
  -- `M.list()` (and `M.refresh()`'s scanner) silently skips
  -- files whose YAML frontmatter fails to parse or whose
  -- decoded body fails schema validation — correct behavior for
  -- consumers that just want validated data — that silence is
  -- exactly wrong for a panel UI: a single broken save makes
  -- the task disappear from the panel with no indicator, no
  -- error toast, no clue that anything is amiss. `scan()` walks
  -- the same bucket tree (open/deferred/completed/archived) but
  -- partitions: `{ tasks = <validated[]>, malformed = [{
  -- file_path, bucket, filename, err }, ...] }`. Consumers
  -- (auto-finder v0.2.38+) render the malformed rows so the
  -- user can navigate to the file and fix it. M.list() is left
  -- byte-identical for back-compat. Section [58b] smoke adds
  -- 17 assertions covering: bucket assignment, entry shape,
  -- list/scan divergence, missing-dir safety. Strictly additive;
  -- `api_version` stays at `0.1`.
  -- v0.1.39 (2026-05-26): tolerant-reader scalar→list coercion for
  -- the three list-of-string frontmatter fields (`tags`, `adr`,
  -- `blocked`) PLUS educational error messages for genuine
  -- type mismatches.
  --
  -- Motivating frustration: a human writing ONE ADR reference
  -- naturally types
  --     adr: shared/adrs/0031-foo.md
  -- not
  --     adr:
  --       - shared/adrs/0031-foo.md
  -- Pre-v0.1.39 this caused the validator to iterate the scalar
  -- character-by-character (since string is sequence-able in Lua),
  -- producing bogus `errors[]: not-found` rows, or — post-v0.1.38 —
  -- routed the task into the panel's malformed section with the
  -- terse `expected list of strings, got string` message. Neither
  -- told the user how to repair the file.
  --
  -- Two layered changes:
  --   1. `lua/auto-core/todo/md.lua` — after YAML decode but
  --      before the schema sees the table, any NON-EMPTY scalar
  --      string in `tags` / `adr` / `blocked` is wrapped into a
  --      1-element list. The next M.encode normalizes it to the
  --      canonical list form on disk. Empty strings are NOT
  --      coerced (`adr: ''` doesn't silently create a `{ "" }`
  --      bogus entry). Numbers, booleans, mappings flow through
  --      and hit step 2.
  --   2. `lua/auto-core/todo/schema.lua` `is_string_list` — the
  --      three failure-mode messages (wrong outer type, mapping
  --      not sequence, non-string item) now each include a
  --      multi-line YAML list-form hint so a genuinely-broken
  --      value tells the user EXACTLY how to repair the file
  --      (with copy-pasteable indented `- entry` snippet).
  --
  -- Section [58a] adds 7 assertions for coercion + round-trip +
  -- the empty-string non-coercion invariant; [58c] adds 8
  -- assertions for the educational error messages. Strictly
  -- additive — schema v1 unchanged, file format unchanged,
  -- existing list-form files round-trip byte-identical.
  -- `api_version` stays at `0.1`.
  -- v0.1.40 (2026-05-26): `auto-core.todo.vars` submodule —
  -- per-machine variable store + `$VAR/...` path resolver.
  -- Closes the portability gap that left `.todo-list/` shareable
  -- via git in name only: an absolute path encoded in a task
  -- file (`adr: /Users/alice/.../kb/shared/adrs/...`) breaks on
  -- every other machine, and a KB-relative path (`adr:
  -- shared/...`) requires identical env-var setup on every
  -- machine that opens the file.
  --
  -- Wire format: a task references docs as
  --     adr:
  --       - $KB_ROOT/shared/adrs/0031-foo.md
  -- The variable NAME (KB_ROOT) is committed to git; its VALUE
  -- is local-machine state (`auto-core.state.namespace('todo.vars',
  -- {persist='json'})`, never enters git).
  --
  -- Surface:
  --   - `vars.BUILTINS`           — { KB_ROOT, WORKSPACE, HOME, CWD }
  --     auto-resolved, read-only.
  --   - `vars.get(name)`          — built-in → state → vim.env,
  --     first non-nil wins.
  --   - `vars.set(name, value)`   — user-defined only; rejects
  --     built-in names; rejects names that aren't valid shell
  --     identifiers (`[A-Za-z_][A-Za-z0-9_]*`).
  --   - `vars.remove(name)`       — user-defined only.
  --   - `vars.list()`             — built-ins first, then user
  --     vars lexicographically.
  --   - `vars.resolve_path(input)` — primary path-resolution API.
  --     Detects `$VAR/...` and `${VAR}/...` prefixes. Returns
  --     `{ ok, path, var_name, unresolved }`.
  --   - Re-exposed at `todo.vars` via a lazy-loading proxy.
  --
  -- Refresh integration: the `adr` + `review` reference-
  -- validation passes now route every entry through
  -- `vars.resolve_path` BEFORE existence-checking. Unresolved
  -- variables surface as `errors[]` with the new code
  -- `unresolved-variable`. Schema's `VALID_ERROR_CODE` extended
  -- to `{not-found, unresolved-variable}`.
  --
  -- New event topic: `core.todo.vars:changed` payload `{ kind =
  -- 'set'|'remove', name }`. auto-finder v0.2.39 subscribes.
  --
  -- Strictly additive — `VALID_ERROR_CODE` was already a closed
  -- set rejecting unknown codes, so existing files (only
  -- `not-found` from prior validators) continue to validate.
  -- Smoke section [65] adds assertions covering built-in
  -- resolution, user-var CRUD, env-var fallback, `${VAR}` brace
  -- form, and unresolved-variable error emission.
  -- `api_version` stays at `0.1`.
  -- v0.1.41 (2026-05-26): `$KB_ROOT` resolver gains a Lua-API
  -- fallback: when the AUTO_AGENTS_KB_* env vars are unset on the
  -- nvim process (the common case in the PARENT nvim — env vars
  -- are only injected into spawned agent processes), try
  -- `require('auto-agents.kb').root()` via pcall. That function
  -- reads from auto-agents.nvim's TOML config and returns the
  -- same path the spawn step would inject. Soft dependency —
  -- installs without auto-agents.nvim still work (just no
  -- fallback). No new schema/event/surface. `api_version` stays
  -- at `0.1`.
  -- v0.1.42 (2026-05-26): expand `kb-todo-list` importer's
  -- status-atom vocabulary. ADR §6 documented only
  -- `open / blocked / closed`, but real KBs accumulated other
  -- finalized-state atoms (`completed`, `resolved`, `done`,
  -- `superseded`) plus paused-work variants (`deferred`,
  -- `paused`, `wip`). Pre-v0.1.42 these all defaulted to
  -- `open`, so a Phase-4 migration sweep imported finished
  -- work as if it were active. Strictly additive — every
  -- previously-recognized atom maps the same way; new ones
  -- stop defaulting to `open`. `api_version` stays at `0.1`.
  -- v0.1.43 (2026-05-26): `auto-core.todo.assign(id, assignee,
  -- reason?)` + new event topic `core.todo.assignee:changed`.
  -- Per ADR §5 + lector S1, ONLY the assign API path emits the
  -- event; direct YAML `assignee:` edits stay metadata-only.
  -- Event payload: `{id, title, file_path, from, to, reason,
  -- at}` — auto-agents v0.2.37 subscribes to deliver a one-shot
  -- mailbox message to the recipient's inbox. Strictly
  -- additive; `api_version` stays at `0.1`.
  -- v0.1.44 (2026-05-26): permit `.` as a namespace separator
  -- in mailbox command names. Pre-v0.1.44 validator pattern
  -- `[A-Za-z_][A-Za-z0-9_-]*` rejected `todos.list`, etc.,
  -- which blocked auto-agents v0.2.37's todos.* surface.
  -- New pattern: `[A-Za-z_][A-Za-z0-9_.-]*` + safety checks
  -- (no consecutive dots, no trailing dot). Strictly additive
  -- — every previously-valid name is still valid.
  -- `api_version` stays at `0.1`.
  -- v0.1.45 (2026-05-26): `mailbox.commands.list()` now includes
  -- each command's `schema` (the `{field = type}` arg-shape hint
  -- declared at register time). Pre-v0.1.45 it returned only
  -- name/owner/description, so discovery consumers (`commands_list`)
  -- couldn't tell agents which args a verb takes — agents guessed
  -- and hit `bad_args`. The schema makes the command surface
  -- self-describing. Shallow-copied per entry so callers can't
  -- mutate the registry. Strictly additive — existing consumers
  -- that read only name/owner/description are unaffected.
  -- `api_version` stays at `0.1`.
  -- v0.1.46 (2026-05-26): two todo-handling follow-up fixes,
  -- bundled.
  --
  -- (a) `add` / `update` / `remove` now publish a new
  --     `core.todo:changed` event (payload `{ kind, id }`).
  --     Pre-v0.1.46 only `status` / `assign` / `refresh` fired,
  --     so a task created via the API or the `todos.add` mailbox
  --     verb never reached the auto-finder panel until some other
  --     event triggered a render (follow-up #4).
  --
  -- (b) `adr` / `review` document references are normalized to
  --     the portable `$VAR/...` symbolic form on write (add /
  --     update, and self-healing on refresh). Agents reliably
  --     know the ABSOLUTE path but guess the wrong `$KB_ROOT`
  --     prefix; now they can supply an absolute (or bare KB-rel)
  --     path and the host rewrites it. Resolution order:
  --     $KB_ROOT → $WORKSPACE → user-defined vars → $HOME,
  --     longest-prefix wins; absolute kept only when NO known
  --     root contains the path. $CWD excluded (volatile). Closes
  --     the "agent adds adr without basepath → panel can't open
  --     it" report.
  --
  -- Strictly additive — new event topic + a write-time
  -- normalization that produces schema-valid output (symbolic
  -- refs already validated since v0.1.40). `api_version` stays
  -- at `0.1`.
  -- v0.1.47 (2026-05-26): expose `auto-core.todo.vars.symbolize_path`
  -- — the inverse of `resolve_path`. It rewrites an absolute (or
  -- bare KB-/WS-relative) path to the portable `$VAR/...` form
  -- (KB_ROOT → WORKSPACE → user vars → HOME, longest-prefix wins;
  -- $CWD excluded; absolute kept only when no root matches). The
  -- v0.1.46 todo `adr`/`review` normalization was a local copy of
  -- this logic; it now delegates to the shared API so writers
  -- (todo normalization) and display consumers (auto-agents diff
  -- panel winbar, v0.2.44+) share one implementation. Strictly
  -- additive. `api_version` stays at `0.1`.
  -- v0.1.48 (2026-05-27): todo `review` frontmatter widened from a
  -- single string to a list (string_list), matching `adr`. Motivating
  -- need: multi-repo / multi-agent tasks carry more than one review
  -- doc, but the schema only accepted one. Four changes in the todo
  -- subsystem:
  --   - schema.lua: `review` kind `string_or_null` → `string_list`.
  --   - md.lua: `review` added to the tolerant-reader LIST_FIELDS, so
  --     a legacy scalar `review: <path>` coerces to a 1-element list on
  --     read (back-compat) and the writer emits canonical list form on
  --     next write. yaml.encode already block-emits table values.
  --   - todo/init.lua: `normalize_ref_paths` + the refresh existence-
  --     check iterate `review[]` per-entry (portable `$VAR/...`
  --     rewrite + `review[i]` not-found / unresolved-variable errors),
  --     mirroring the `adr[]` handling.
  -- Back-compat: existing `review: <string>` files read as 1-element
  -- lists; only a DOWNGRADE reading list-form `review` would flag
  -- errors. Smoke [55]/[58a]/[58d] extended (review list happy/reject,
  -- scalar→list coercion, per-entry path normalization); suite green
  -- at 1110 passed, 0 failed. The consumer-side render lands in
  -- auto-finder v0.2.47. The schema field-kind widens with read
  -- coercion rather than break-shaping existing data; `api_version`
  -- stays at `0.1` consistent with the v0.1.x todo additions.
  -- (v0.1.49–v0.1.56: see CHANGELOG.md — the in-file log lagged the
  -- git tags for those releases; resynced here at v0.1.57.)
  -- v0.1.57 (2026-06-11): ADR-0038 Batches A–C — correctness +
  -- performance pass from the full v0.1.56 audit. Strictly additive;
  -- `api_version` stays at `0.1`.
  --   Batch A (correctness):
  --   - ui/float/multi.lua + ui/panel.lua with_unfixed_buf: ALL
  --     window-option writes now scope-local per ADR-0028. The
  --     with_unfixed_buf restore leg previously mutated the GLOBAL
  --     winfixbuf default ("winfixbuf propagation" bug — every window
  --     created after a section mount was born buffer-locked).
  --   - mailbox/router.lua executioner: transport.complete() failures
  --     are now logged + published as NEW additive topic
  --     `core.mailbox:response_write_failed` (previously fully silent;
  --     the sender polled its responses/ dir forever).
  --   - mailbox/router.lua: the poll fallback timer re-arms when
  --     `poll_interval_ms` changes (was frozen at first-armed value).
  --     `router.status()` gains `poll_armed_interval_ms`.
  --   Batch B (mailbox UI responsiveness):
  --   - mailbox/ui.lua: event-driven refresh coalesced (250ms) — an
  --     event burst repaints once, not N times.
  --   - mailbox/transport.lua list_entries: per-(mailbox,subdir) entry
  --     cache keyed on a scandir name:mtime:size signature — an
  --     unchanged dir returns prior entries with ZERO file decodes.
  --     Decoded fields normalized string-or-nil at the boundary
  --     (JSON null → vim.NIL userdata previously crashed the viewer's
  --     renderer). Adds _invalidate_entry_cache() + _list_decode_count
  --     test hooks.
  --   Batch C (todo I/O consolidation):
  --   - todo/paths.lua: NEW `walk(td, on_file, bucket_filter?)` +
  --     `find_task_file(td, id)` — the single canonical bucket
  --     walk/find. todo/init.lua's three hand-rolled walk copies
  --     (list/scan/walk_task_files) and automation.lua's private
  --     bucket scan all delegate (the duplication class that shipped
  --     the v0.1.47 override-dir bug).
  --   - todo/init.lua add(spec, internal?): internal second parameter
  --     lets auto-core-internal callers stamp the managed `origin`
  --     INTO the create write; automation clone-on-fire drops its
  --     post-create read/modify/write round-trip and the backref is
  --     crash-durable from birth.
  -- Smoke [75] added (25 assertions); suite at 1300 passed. The 4
  -- failures on the dev machine pre-exist on main (macOS env issues:
  -- max_handles cap, fan_out sort, prune ×2 — tracked in the KB todo
  -- 2026-05-26-fix-macos-symlink-resolution-failures-in-smoke-tests).
  -- v0.1.58 (2026-06-11): ADR-0038 Batches D1 + E. Strictly additive;
  -- `api_version` stays at `0.1`.
  --   Batch D1 (async git show):
  --   - git/graph.lua: NEW `show_stat_async` / `show_diff_async` —
  --     same per-(common_dir, hash) caches as the sync APIs, run via
  --     vim.system off the UI thread, cb on the main loop. Concurrent
  --     same-key requests coalesce into ONE subprocess. Sync APIs
  --     unchanged; consumers (worktree.nvim graph) migrate at their
  --     own pace. `_async_spawn_count` test hook.
  --   Batch E (structural hygiene):
  --   - NEW fs/atomic.lua — the single canonical write-temp→fsync→
  --     rename primitive (`fs.atomic.write(path, text, {mkdir?})`),
  --     exposed on the `fs` facade. transport / bootstrap / todo
  --     delegate (previously three drifting inline copies).
  --   - state/init.lua: one memoized events() resolver replaces the
  --     four inline `require("auto-core").events` facade round-trips.
  --   - todo/schema.lua now OWNS the frontmatter catalog: exports
  --     FRONTMATTER_ORDER next to FIELDS with a load-time drift
  --     check; todo/md.lua consumes it (previously a hand-synced
  --     copy in each file).
  --   - router: refresh() sweeps the seen/debounce bookkeeping maps
  --     (seen ids whose files left the subdir; debounce stamps older
  --     than 1h); `status()` gains seen_total / debounce_total.
  --   - log: throttle map size-gated opportunistic prune (512-entry
  --     threshold, 1h TTL, same pattern as fs/watch); `_throttle_size`
  --     test hook.
  --   - ADR-0038 S5 decided DOCUMENT-ONLY: todo.add/update validate
  --     shape, not reference existence — broken adr/review/blocked
  --     refs surface as errors[] on refresh/scan (contract now stated
  --     in the add() docstring).
  -- Deferred: D2 (async fan_out — latency not felt at current repo
  -- counts), F (test-suite split), todo list() TTL memoize.
  -- Smoke [76] added (19 assertions); suite at 1319 passed (same 4
  -- pre-existing macOS env failures as the v0.1.56/57 baselines).
  -- v0.1.59: ADR 0042 — fs.watch self-extending recursion (Linux
  -- walker). The Linux walker previously opened one fs_event handle
  -- per subdir that existed at start() and never extended to dirs
  -- created later; inotify being non-recursive, files written into a
  -- runtime-created subtree (fresh worktree / git clone / mkdir) fired
  -- no `core.file:*` event until a full rescan. Fixed the reported
  -- auto-finder files-panel blindness to new worktrees/repos. Now the
  -- fs_event callback detects directory-creation events and grows the
  -- watch set: walks the new subtree (C2), opens a handle per
  -- not-yet-watched, non-ignored dir (directory-form ignore match, C3)
  -- within `max_handles` (C4), catch-up-emits entries that predated the
  -- handle (C6), and reclaims handles when a watched dir is deleted (C5).
  -- Strictly additive:
  --   - `events/topics.lua` registers NEW `core.fs.watch:partial`
  --     payload `{ root, path, active, attempted, dropped, max }` —
  --     emitted (with a warn log) when the cap stops self-extension
  --     mid-subtree, so consumers can surface degraded live refresh.
  --   - `fs/watch.lua` AutoCoreWatchOpts gains `self_extend` (default
  --     true); set false to keep the start-time-only baseline.
  --   - AutoCoreWatchHandle gains `_watched_dirs` (dir → handle).
  -- The Darwin handler is untouched — its single recursive FSEvents
  -- watch already covered runtime subtrees; the whole fix and its
  -- smoke section [26b] are Linux-gated. No removals, no break-shape;
  -- consumers that never create dirs under a watch pay nothing.
  -- Lector-reviewed (approved_with_amendments, all 6 folded in).
  -- Smoke [26b] added (9 assertions, Linux); suite 1329 passed / 3
  -- pre-existing todo-archive failures (identical on the v0.1.58 main
  -- baseline — unrelated to fs.watch). Patch within the v0.1.x line
  -- per `auto-core-maintenance`; `api_version` stays at `0.1`.
  version     = "0.1.59",
  api_version = "0.1",
}
