---Version + API-version metadata for auto-core.nvim.
---
---`version` is the package version (`v0.X.Y` git tag — used by lazy.nvim
---when consumers pin via `version = "^0.X.0"`). It bumps on every
---release.
---
---`api_version` is a SEPARATE semver string covering the public Lua
---surface (`require("auto-core").events`, `.state`, `.ui`, `.fs`,
---`.git`, `.tasks`, `.log`, `.health`). It bumps independently of
---`version`:
---  - patch: bug fixes only, no API change
---  - minor: API additions (new functions, new topics, new state keys)
---  - major: API removals or behavior changes
---
---Consumers branch on `api_version` when they need feature-detection
---without pinning a specific package version:
---
---  if require("auto-core").api_version >= "0.2" then ... end
---
---v0.1.0 (2026-05-11) is the **solid beta** — first release covered
---by the `auto-core-maintenance` convention's additive-only minor-
---bump rule. Consumers can safely pin via `version = "^0.1.0"` (caret)
---and trust that no future v0.X.Y will rename, remove, or break-shape
---any existing function, state key, topic, or persisted schema.
---
---@module 'auto-core.version'

return {
  -- v0.1.8: per-instance mailbox isolation. `register("agent:foo")`
  -- now stores the mailbox under `<root>/agent:foo:<instance_id>/`
  -- where instance_id = `<unix-seconds>-<pid>` for this nvim
  -- process. Two nvims sharing a tool root coexist cleanly — no
  -- lock, no cross-talk, hard-isolation by directory. Bootstrap
  -- doc hoisted to `<tool-root>/bootstrap-mailbox.md` (shared
  -- across all mailboxes in that root) with agent identity now
  -- carried via spawn-time env vars rather than per-call template
  -- substitution. Adds `mailbox.env_for_agent(record)` and
  -- `mailbox.prune({ root, max_age_seconds })` helpers. Event
  -- payloads carry bare ids in `mailbox` / `from` fields with
  -- `_full` / `_resolved` companions for cross-instance routing.
  -- Persisted schema change (mailbox dir layout) shipped as patch
  -- per user decision; only known consumer (auto-agents) updates
  -- alongside.
  -- v0.1.9: bootstrap template update. The agent-facing protocol
  -- doc (`templates/bootstrap.md`) now references `wake` instead
  -- of `send_slot` as the canonical wake command name and adds a
  -- new section explaining the `addressbook` discovery command.
  -- schema_version bumped 2 → 3 because the renamed command name
  -- is a public-API contract change agents must re-acknowledge.
  -- No Lua-API change — `mailbox.commands.register` consumers
  -- (auto-agents v0.2.8+) already register `wake` + `addressbook`
  -- with the registry.
  -- v0.1.10: git.graph.fan_out — `is_bare` now reflects the
  -- underlying repo's bareness (read from `<common_dir>/config:
  -- core.bare`) rather than the probed dir's. Probing from inside
  -- a linked worktree of a bare repo previously returned
  -- is_bare=false because `rev-parse --is-bare-repository` reports
  -- the working-tree's bareness, not the repo's — causing
  -- worktree.nvim's `C` (checkout) keybind to fall into the plain
  -- `git checkout` branch instead of `git worktree add --track`.
  -- No API shape change; AutoCoreGraphRepo.is_bare semantics
  -- clarified, not renamed.
  -- v0.1.11: ADR 0021 Phase 1 — centralized log surface for the
  -- family. Additive extensions to `auto-core.log` (no removals,
  -- no break-shape):
  --   - AutoCoreLogEntry gains optional `event_type` and `fields`
  --     fields; both nil for pre-ADR-0021 emissions
  --   - level_call accepts a trailing options table whose
  --     recognition is keyed on sentinel keys (event / fields /
  --     notify / level_override); ordinary message-part tables
  --     keep rendering via vim.inspect unchanged
  --   - log.notify(msg, opts?) — single-emission ring write +
  --     forced vim.notify toast
  --   - log.notifyIf(event, msg, opts?) — ring write + toast iff
  --     event is in the user's subscribed set
  --   - log.events.{register, list, enable_notify,
  --     disable_notify, is_notify_enabled} — plugin-registered
  --     event registry; subscriptions persist via
  --     auto-core.state.namespace("auto-core.log.events")
  --   - log.<level>_throttled(key, every_ms, ...) — hot-loop guard
  --     family for every level
  --   - :AutoCoreLogEvent list | notify <event> | silence <event>
  --     user command with context-aware tab completion
  -- See ADR 0021 + shared/conventions/auto-family-logging.md for
  -- the wrapper convention each consumer plugin should follow.
  -- v0.1.12: mailbox.router executor `ctx` now surfaces the
  -- sender's identity as `sender` (msg.from verbatim) and
  -- `sender_bare` (`mb_path.bare_id(from)`) alongside the existing
  -- `mailbox` / `mailbox_full` executor fields. Closes a latent
  -- attribution gap: command handlers that wanted "who asked me to
  -- do this" had to guess from `ctx.mailbox`, which is the EXECUTOR
  -- (always `nvim`), not the sender. Surfaced for the auto-agents
  -- `diff_queue` handler — see auto-agents v0.2.12 Patch 4 + ADR
  -- 0011 §D3 for the consumer side. Additive; no removals; existing
  -- consumers reading `ctx.mailbox` continue to work unchanged.
  -- v0.1.13: ADR 0023 Phase 1 + log :messages silence. Three
  -- additive changes:
  --   1. `log.lua`: INFO+ is RING-ONLY by default — toasts no
  --      longer leak to `:messages` unless caller passes
  --      `opts.echo = true` (per-call) or `configure({ echo =
  --      true })` (global). ERROR + WARN still toast as before.
  --      Pre-v0.1.13 behavior was firehose `:messages` echo on
  --      every emission; new default mirrors the
  --      auto-family-logging convention's "no noisy :messages"
  --      stance.
  --   2. `mailbox/router.lua`: classify() now emits the new event
  --      topic `mailbox.stale_orphan_detected` whenever a poll
  --      finds an outbox path whose mailbox component matches a
  --      KNOWN bare id but at a NON-CURRENT instance suffix.
  --      Payload carries `{ mailbox_bare, observed_instance,
  --      current_instance, path }`. Subscribed via
  --      `auto-core.log.events` for the resumed-agent diagnostic
  --      (per ADR 0023 §3.1). Existing classification outcomes
  --      unchanged; this is a pure observability addition.
  --   3. `mailbox/router.lua` + `templates/bootstrap.md`: wake
  --      payloads now carry `identity_hint` (the live full
  --      mailbox id) so resumed agents can detect drift between
  --      their fork-frozen `$AUTO_AGENTS_MAILBOX_DIR` env and the
  --      actual mailbox the host expects them to read. Bootstrap
  --      doc gains §"Resumed-agent identity reconciliation"
  --      documenting the drift, the new event, the `identity_hint`
  --      field, and the auto-agents `refresh_agent_id` verb (the
  --      latter shipped in auto-agents v0.2.13). Bootstrap
  --      schema_version bumped 4 → 5; resumed agents will see
  --      revision mismatch on next wake and re-ingest. See ADR
  --      0023 §3.1 / §3.2 / §4 for the full design.
  -- All three are additive. No removals; no break-shape; existing
  -- consumers ride through unchanged. Per
  -- `auto-core-maintenance`'s additive-only minor-bump rule this
  -- is a patch within the v0.1.x line. `api_version` stays at
  -- `0.1`.
  -- v0.1.14: six new `dbase.*` event topics registered in
  -- `lua/auto-core/events/topics.lua` for the auto-finder dbase
  -- section (ADR 0020) to publish onto:
  --   - dbase.connection:changed
  --   - dbase.call:started
  --   - dbase.call:state_changed
  --   - dbase.call:completed
  --   - dbase.call:failed
  --   - dbase.result:shown
  -- `conn_id` is marked optional (`string?`) on all four call.*
  -- topics because dbee's `CallDetails` shape carries no connection
  -- id; the bridge enriches via `get_current_connection()` which can
  -- return nil for archived/late events. Additive — no removals, no
  -- break-shape. Patch within the v0.1.x line per
  -- `auto-core-maintenance`; `api_version` stays at `0.1`.
  -- v0.1.15: bootstrap mailbox protocol doc now directs agents to
  -- persist `seen-revision` beside the shared per-tool-root
  -- `bootstrap-mailbox.md`, not only inside the instance-scoped
  -- mailbox dir. Bootstrap schema_version bumped 5 → 6 so agents
  -- re-read the corrected audit instructions. Additive doc-only
  -- patch; `api_version` stays at `0.1`.
  -- v0.1.16: panel-guard observability — every bounce + lifecycle
  -- event in `lua/auto-core/ui/panel.lua` now emits via `log.lua`
  -- so incident triage sees the full chain in the ring. Additive
  -- diagnostic-only patch; `api_version` stays at `0.1`.
  -- v0.1.17: ADR 0021 Phase 4 — `:AutoCoreLog` 3-pane snapshot
  -- viewer + JSONL dump persistence. Two new modules under
  -- `lua/auto-core/log/`:
  --   - dumps.lua — atomic JSONL export under
  --     `stdpath('cache')/auto-core/dumps/dump-<UTC>.log`. ISO 8601
  --     UTC timestamps reconstructed at export via
  --     `now_wall - (now_mono - ts) / 1000`. `dumps.{dir, scan,
  --     read, write, delete, iso_from_mono, normalize_for_disk}`.
  --   - viewer.lua — 3-pane float over `auto-core.ui.float.multi`
  --     (left = dump list, middle = entries, preview = detail).
  --     `viewer.{open, close, toggle, is_open}`. Snapshot
  --     semantics (no live tail). Bindings: 1..9 / <CR> / E / D /
  --     R (re-snapshot Memory — ADR §16 Q2 = yes) on left;
  --     / and f (substring + level filter cycle) on middle;
  --     <Tab> / <S-Tab> / <C-h> / <C-l> on any. q / <Esc>
  --     inherited from `ui.float.multi`.
  -- `:AutoCoreLog [open|close|toggle]` registered in
  -- `plugin/auto-core.lua`. Stale "Phase 1 stub" comment on
  -- `M.notifyIf` docstring scrubbed (registry shipped through
  -- v0.1.14). 44 new smoke tests across sections [50] dumps + [51]
  -- viewer; suite green at 718 passed, 0 failed. Additive — no
  -- removals, no break-shape, existing consumers ride through
  -- unchanged. Patch within v0.1.x per `auto-core-maintenance`;
  -- `api_version` stays at `0.1`.
  -- v0.1.19: ADR 0025 Phase 1 — `auto-core.git.watch` module +
  -- `core.git.state:changed` topic. Closes the refresh-trigger gap
  -- that left UI consumers (auto-finder files panel) showing stale
  -- git decorations after external `git add`/`commit`/`checkout`/
  -- `reset`: `auto-core.fs.watch`'s `DEFAULT_IGNORE` excludes
  -- `/.git/` by design, so no `core.file:*` ever fires for `.git/`
  -- mutations. Three additive changes:
  --   - `lua/auto-core/git/watch.lua` — narrow opt-in watcher that
  --     opens two non-recursive libuv `fs_event` handles per repo
  --     (git_dir/ filtered to {HEAD,index,ORIG_HEAD,MERGE_HEAD};
  --     git_dir/logs/ filtered to "HEAD"). Resolves git_dir via
  --     `git.repo.git_dir(repo_root)` so linked worktrees attach
  --     per-worktree, not to common_dir. `.lock` filenames are
  --     filtered at the publisher. Debounce 200ms. Public surface
  --     mirrors `fs.watch.start/stop/list/stop_all` + defaults.
  --   - `events/topics.lua` registers `core.git.state:changed`
  --     payload `{ repo_root, git_dir, kind = 'head'|'index'|
  --     'merge'|'reflog'|'other', path }`. Single coarse topic;
  --     `kind` discriminator lets subscribers filter.
  --   - `git/status.lua` adds a second `events.subscribe` for the
  --     new topic to invalidate its cache (the existing
  --     `core.file:*` invalidation misses `.git/`-only mutations
  --     for the same reason — fs.watch ignores them).
  -- Refs/remotes/, FETCH_HEAD, and logs/refs/remotes/ deliberately
  -- NOT watched — `git fetch` updates those and ADR 0007 Phase 3.5's
  -- `core.git.fetch:completed` already covers that case. Per ADR
  -- 0025 §2.5, `auto-core.fs.watch`'s `/%.git/` ignore stays
  -- untouched (un-ignoring would flood every subscriber with
  -- object/refs/reflog churn). Additive — no removals, no
  -- break-shape; consumers that don't call `git.watch.start` pay
  -- nothing. Section 51 smoke covers start/stop, kind classification
  -- across index/reflog/head, refs/remotes/ exclusion, .lock filter,
  -- debounce coalescing, max_handles cap, and status cache
  -- invalidation via the new topic. Suite green at 744 passed,
  -- 0 failed. Patch within v0.1.x per `auto-core-maintenance`;
  -- `api_version` stays at `0.1`.
  -- v0.1.18: ui.panel resize/lifecycle observability. New ring
  -- emissions in `lua/auto-core/ui/panel.lua`:
  --   - INFO `VimResized — terminal geometry changed` (host
  --     terminal resize: tmux pane / wezterm split / kitty grow).
  --     Anchors "what was the screen state when X happened".
  --   - DEBUG-throttled `WinResized fired` (per-panel, 250ms
  --     debounce key). Records `v:event.windows` so we see exactly
  --     which winids moved during a drag.
  --   - INFO `pin enforced — width re-clamped` when `enforce_pin`
  --     actually bounces a width back to the user pin (was silent
  --     before — sibling-plugin `:wincmd =` events left no trace).
  --   - INFO `panel window closed externally` on `WinClosed` for
  --     the panel's own winid. Catches close paths that bypass
  --     `Panel:close()` and would otherwise leave singleton
  --     tracking out of sync.
  -- Additive diagnostic-only patch; `api_version` stays at `0.1`.
  -- v0.1.21: ui.panel visibility-gap fix per yongjohnlee80/auto-agents
  -- issue #3 + incident
  -- agents/white-vision/incidents/2026-05-18-auto-agents-panel-duplicated-recurrence.md.
  -- Three changes to `lua/auto-core/ui/panel.lua`:
  --   - Defensive VimResized handler closes a regression that
  --     shipped silently with v0.1.18. The original form's
  --     field-table literal evaluated
  --     `(p:_is_open() and nvim_win_get_width(p.winid)) or nil`
  --     INSIDE the `{ fields = { ... } }` literal. When `p.winid`
  --     was racy-invalid (panel closed mid-handler), the field
  --     evaluation threw BEFORE `log_panel.info` ever ran — and
  --     the autocmd's implicit pcall swallowed the error. Net
  --     result: zero VimResized log entries in real session ring
  --     dumps despite the autocmd being correctly registered.
  --     The new form logs FIRST, computes throwable fields via
  --     explicit pcall, then refreshes width. The anchor now
  --     lands reliably.
  --   - New WinNew autocmd on the panel singleton's autocmd
  --     group. Deferred via `vim.schedule` so the new window's
  --     buffer is stable at check time. Logs INFO with
  --     `sibling_winids`, `panel_winid`, `panel_bufnr`,
  --     `marker_var`, `columns`/`lines`, and
  --     `debug.traceback("", 2)` whenever a new non-floating
  --     window appears holding the panel's tracked buffer but
  --     lacking the panel marker. Closes the visibility gap from
  --     the issue #3 investigation — previously these reflow-
  --     created siblings were invisible to the singleton's
  --     logging path because they bypassed `Panel:open()`.
  --     Detection-only — doesn't close; pairs with the next item.
  --   - New `Panel:_cleanup_unmarked_siblings()` method
  --     scheduled via `vim.schedule()` from the VimResized
  --     handler. Scans the tab for windows holding the panel's
  --     tracked buffer but lacking the marker; closes them.
  --     Runs OUTSIDE the autocmd context so `nvim_win_close` is
  --     permitted (avoids the E1312 fallback-scratch-swap dance
  --     that left the duplicate window visible in v0.1.18-v0.1.20).
  --     Logs INFO on each close; silent fast-path when no
  --     siblings exist.
  -- Section [52] smoke adds 11 assertions covering all three
  -- paths. Suite 753 passed, 0 failed. Additive — no removals,
  -- no break-shape. `api_version` stays at `0.1`. Reviewed by
  -- `agent:lector` 2026-05-18 10:30 UTC — approved.
  -- v0.1.22: Lector follow-ups from the v0.1.21 review. Two
  -- non-blocking observations addressed:
  --   - `_cleanup_unmarked_siblings` now scans
  --     `nvim_tabpage_list_wins(0)` (current tab only) instead of
  --     `nvim_list_wins()` (all tabs). Aligns with the incident
  --     language and prevents a theoretical cross-tab race where a
  --     sibling editor split in tab B holding the panel buffer
  --     would be force-closed by a VimResized cleanup pass in tab A.
  --     Panels are tab-singletons in the auto-family model; the
  --     load-bearing reflow case is intra-tab only.
  --   - Smoke section [52] now exercises the WinNew detection log
  --     path explicitly (assertion `WinNew detection logged
  --     'unmarked sibling detected (WinNew)'` + `WinNew detection
  --     did NOT close the sibling (detection-only)`). Previously
  --     the section only covered the cleanup path. Section grows
  --     11 → 13 assertions. Suite 755 passed, 0 failed.
  -- Additive; api_version stays at 0.1.
  -- v0.1.23: mailbox.router executor `ctx` now also surfaces
  -- `correlation_id` (from `claimed.correlation_id`) and `message_id`
  -- (executor-path file basename) alongside the v0.1.12 `sender` /
  -- `sender_bare` fields. Closes the round-trip-identity gap for
  -- handlers that defer a user-driven verdict past the synchronous
  -- response: auto-agents' `diff_queue` stashes both on its queue
  -- entry so the eventual reject/accept emits a follow-up message
  -- back to the originator via the standard router. Additive — no
  -- removals; existing handlers reading only `sender_bare` continue
  -- to work unchanged. Consumer side ships in auto-agents v0.2.19.
  -- `api_version` stays at `0.1`.
  -- v0.1.24: mailbox router + commands log observability. Closes
  -- the silent-router gap that left wake dispatch + command
  -- execution invisible to `:AutoCoreLog` (motivating incident:
  -- 2026-05-18 claude-backed agents Ultron + Vision missed wake
  -- nudges with zero ring entries to triage from). Two modules
  -- gain log emissions; one new event-type set is registered:
  --   - `mailbox/router.lua` — INFO on every inbox arrival
  --     (`mailbox.router.inbox_arrival`), response arrival
  --     (`mailbox.router.response_arrival`), and wake dispatch
  --     (`mailbox.router.wake_dispatched`). DEBUG when wake
  --     short-circuits on a mailbox with no wake config; WARN
  --     when wake's `wake.command` references a command not in
  --     the registry (almost always a setup-order bug).
  --   - `mailbox/commands.lua` — `M.handle_message` refactored
  --     into a logging-free `_handle_message_inner` + a thin
  --     outer that emits one structured entry per call:
  --     `mailbox.commands.command_executed` (INFO on ok=true /
  --     ERROR on `handler_error` / WARN otherwise) or
  --     `mailbox.commands.command_rejected` (WARN, covers
  --     `bad_message`, `not_a_command`, `missing_command`,
  --     `bad_args`, `unknown_command`).
  --   - `plugin/auto-core.lua` — registers all six event types
  --     under the `auto-core` plugin slug so
  --     `:AutoCoreLogEvent list` surfaces them. Subscribe via
  --     `:AutoCoreLogEvent notify <event>` to also see them as
  --     toasts (off by default — emissions are ring-only INFO).
  -- Structured fields on every entry: `mailbox`, `mailbox_full`,
  -- `arrival_kind`, `arrival_id`, `command`, `ok`, `code`,
  -- `error`, `correlation_id`, `dispatch_path` ("mailbox_wake"
  -- vs "mailbox_executioner"), `executor_mbox`. Filterable from
  -- `:AutoCoreLog` by component (`auto-core.mailbox.router` or
  -- `auto-core.mailbox.commands`) or by event id.
  -- Additive — no removals; no break-shape; existing event
  -- topics (`core.mailbox:*`, `core.command:*`) continue to fire
  -- unchanged alongside the new log entries. `api_version`
  -- stays at `0.1`. ADR 0021 §10 (router observability) called
  -- this out as deferred; this is that deferral resolved.
  -- v0.1.25: `ui.section.Registry:section_did_remount(N, bufnr)`
  -- — public hook for async-mount sections to repair their
  -- registry binding after a placeholder→real buffer swap.
  -- Motivating bug: auto-finder's dbase view returns a
  -- `shared.loading` placeholder from `get_buffer()` and swaps
  -- the real dbee drawer in via a `vim.schedule`-deferred mount
  -- from `on_focus`. Without this hook the registry's cached
  -- bufnr, buffer-local `0..9`/`q` keymaps, and panel winbar
  -- all remain bound to the discarded placeholder — the
  -- user-facing symptom is "winbar disappears on first dbase
  -- focus + numeric section-hop stops working" until a later
  -- redraw (`<leader>e` toggle, auto-agents panel open, etc.)
  -- re-triggers `_refresh_winbar`. The new method updates
  -- `_bufs[N]`, re-applies the private `apply_keymap` (only
  -- when N is the active section — keymap surface is
  -- buffer-local), and refreshes the winbar. Idempotent;
  -- short-circuits on invalid bufnr or inactive section.
  -- Additive — no removals, no break-shape; existing
  -- `Registry:focus` path is unchanged. `api_version` stays at
  -- `0.1` — the new method is small enough to ride along with
  -- the v0.1.x line's existing additive contract rather than
  -- flag an api-version minor bump on its own.
  -- v0.1.26: `fs.watch` defaults updated for large bare-repo
  -- parents. Motivating incident: `auto-finder.core.watchers`
  -- logged WARN `fs.watch start failed at <LM root>: would
  -- exceed max_handles cap (0 active + 12318 new > 1024)`; the
  -- recursive walk under a bare-repo parent with ~17 worktrees
  -- of a TS monorepo collected 12k+ dirs even though `node_modules`
  -- + `.git/` + `.bare/` were already ignored. The leftovers were
  -- ecosystem-standard build/cache dirs that everyone wants
  -- ignored. Two additive changes:
  --   - `DEFAULT_IGNORE` gains anchored patterns for `/dist/`,
  --     `/build/`, `/coverage/`, `/target/`, `/%.next/`,
  --     `/%.cache/`, `/%.turbo/`, `/%.parcel%-cache/`,
  --     `/__pycache__/`, `/%.venv/`, `/venv/`,
  --     `/%.pytest_cache/`, `/%.mypy_cache/`, `/%.ruff_cache/`,
  --     `/%.tox/`, `/%.idea/`, `/%.vscode/`. Trims the LM-root
  --     walk by ~15 % and, more importantly, prevents the
  --     known-throwaway subtrees from chewing handles in any
  --     ecosystem-standard project layout.
  --   - `DEFAULT_MAX_HANDLES` raised 1024 → 131072. The cap is a
  --     "catch a runaway bug" belt (`watch.start("/")`), not a
  --     real budget — legitimate large monorepos legitimately
  --     have tens of thousands of source dirs. 131072 = ¼ of
  --     Linux's `fs.inotify.max_user_watches` default (524288),
  --     leaving the other ¾ for everything else under the user's
  --     uid (JetBrains, file managers, other nvim instances).
  --     Callers that want a smaller cap pass `max_handles` to
  --     `watch.start` per call as before.
  -- Strictly additive. Consumers pinning `version = "^0.1.0"`
  -- pick up the change on `:Lazy update` and immediately stop
  -- hitting the cap on large bare-repo parents. Health check at
  -- `health.lua:109` already reads `watch.DEFAULT_MAX_HANDLES`
  -- so the 80 %-threshold warning auto-tracks the new value.
  -- `api_version` stays at `0.1`.
  -- v0.1.27: macOS native-recursive `fs.watch` handler — the
  -- walked-per-directory path used on Linux exhausts the macOS
  -- process fd ceiling around ~7000 dirs, at which point
  -- `vim.uv.new_fs_event` returns nil and the watcher silently
  -- loses coverage. FSEvents supports recursive watching from a
  -- single root handle on Darwin, so we use it there. The
  -- original `fix(fs.watch): use native recursive watcher on
  -- Darwin` commit (dc79b66) added the branch inline inside the
  -- existing walker; it has been reverted on main and the same
  -- logic re-introduced as a separate handler so future Darwin-
  -- only changes cannot perturb the Linux walker. Five additive
  -- changes:
  --   - `fs/watch.lua` IS_DARWIN module-load constant (one
  --     `vim.uv.os_uname()` per process, not per call).
  --   - `fs/watch.lua` `_darwin_start` / `_darwin_start_one` /
  --     `_darwin_join_event_path` — fully segregated handler
  --     section. `M.start` short-circuits into it on
  --     `IS_DARWIN and opts.recursive` BEFORE any walked code
  --     runs. The Linux walker (`start_one_dir`) is byte-
  --     identical to its pre-Darwin shape.
  --   - `fs/watch.lua` `debounce_check` gains an opportunistic
  --     prune. `state._debounce` would otherwise grow without
  --     bound (every unique full_path adds an entry forever).
  --     Pre-Darwin this leaked slowly because the Linux walker
  --     pre-filtered ignored subtrees at walk time; the Darwin
  --     handler routes every event under the subtree through
  --     `debounce_check`, so the leak is much faster on macOS.
  --     New `state._debounce_size` counter triggers an O(N)
  --     sweep (drop entries older than 100×debounce_ms) only
  --     when the live count crosses 4096 — amortized O(1).
  --     Constants `DEBOUNCE_PRUNE_THRESHOLD` /
  --     `DEBOUNCE_PRUNE_TTL_MULT` documented inline.
  --   - `health.lua` `check_fs_watch` reports
  --     `; darwin native-recursive: on` on macOS so a low
  --     active-handle count on the platform doesn't look
  --     suspicious in `:checkhealth auto-core`.
  --   - Docstring header reflects the platform asymmetry: Darwin
  --     auto-watches subdirs created AFTER `watch.start`; the
  --     Linux walker does not.
  -- Strictly additive. The Linux walker code is unchanged
  -- relative to v0.1.26; consumers on Linux pick up only the
  -- debounce prune fix and the health-check copy edit. Consumers
  -- on macOS pick up actual coverage on large workspaces for the
  -- first time. `api_version` stays at `0.1`.
  version     = "0.1.27",
  api_version = "0.1",
}
